//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTF.Application.GunGames {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GunGameMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal GunGameMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTF.Application.GunGames.GunGameMessages", typeof(GunGameMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GunGame started with the &apos;{Progression}&apos; progression ({KillsRequiredPerLevel} kills per level)..
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string GunGameConfiguration {
            get {
                return ResourceManager.GetString("GunGameConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GunGame mode is already active..
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string GunGameModeAlreadyActive {
            get {
                return ResourceManager.GetString("GunGameModeAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GunGame mode has been disabled..
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string GunGameModeDisabled {
            get {
                return ResourceManager.GetString("GunGameModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUN GAME~n~DISABLED.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string GunGameModeDisabledGameText {
            get {
                return ResourceManager.GetString("GunGameModeDisabledGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GunGame mode has finished!.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string GunGameModeFinished {
            get {
                return ResourceManager.GetString("GunGameModeFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUN GAME~n~FINISHED.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string GunGameModeFinishedGameText {
            get {
                return ResourceManager.GetString("GunGameModeFinishedGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GunGame mode is not active..
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string GunGameModeNotActive {
            get {
                return ResourceManager.GetString("GunGameModeNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress through each weapon and score the Final Kill to earn a reward for yourself and your team..
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string GunGameModeObjective {
            get {
                return ResourceManager.GetString("GunGameModeObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GunGame mode has started!.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string GunGameModeStarted {
            get {
                return ResourceManager.GetString("GunGameModeStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUN GAME~n~STARTED.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string GunGameModeStartedGameText {
            get {
                return ResourceManager.GetString("GunGameModeStartedGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of kills required per level must be at least 1..
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string InvalidKillsRequiredPerLevel {
            get {
                return ResourceManager.GetString("InvalidKillsRequiredPerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Killer} knifed {Victim} and demoted them to Level {Level} ({Weapon})!.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string PlayerLeveledDown {
            get {
                return ResourceManager.GetString("PlayerLeveledDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Killer} has advanced to Level {Level} ({Weapon})!.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string PlayerLeveledUp {
            get {
                return ResourceManager.GetString("PlayerLeveledUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Killer} has reached the Final Level ({Weapon})! The Final Kill is next!.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string PlayerReachedFinalLevel {
            get {
                return ResourceManager.GetString("PlayerReachedFinalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Killer} scored the Final Kill and won GunGame!.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string PlayerScoredFinalKill {
            get {
                return ResourceManager.GetString("PlayerScoredFinalKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Team} Team has been rewarded thanks to {Killer}&apos;s Final Kill!.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string TeamRewardGranted {
            get {
                return ResourceManager.GetString("TeamRewardGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team reward: +{Health} Health, +{Armour} Armour, +{Coins} Coins, +{Score} Score..
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string TeamRewardSummary {
            get {
                return ResourceManager.GetString("TeamRewardSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received the GunGame winner reward!.
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string WinnerRewardGranted {
            get {
                return ResourceManager.GetString("WinnerRewardGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner reward: +{Health} Health, +{Armour} Armour, +{Coins} Coins, +{Weapon}..
        /// </summary>
        /// <remarks>Change drivers: CD-17 (root; root; game configuration/.env schema)</remarks>
        internal static string WinnerRewardSummary {
            get {
                return ResourceManager.GetString("WinnerRewardSummary", resourceCulture);
            }
        }
    }
}
