//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTF.Application.Players.GeneralCommands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    /// <remarks>Change drivers: CD-15 (root; command set)</remarks>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DetailedCommandInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailedCommandInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <remarks>Change drivers: CD-15 (root; command set)</remarks>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTF.Application.Players.GeneralCommands.DetailedCommandInfo", typeof(DetailedCommandInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        /// <remarks>Change drivers: CD-15 (root; command set)</remarks>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Color1}/setrole: {Color2}Assigns a specific role to a player.
        ///{Color1}/settotalkills: {Color2}Sets the total kills to a specific player.
        ///{Color1}/setscore: {Color2}Sets the score of a player to a specified value.
        ///{Color1}/addscore: {Color2}Increases the player&apos;s score by a designated amount.
        ///{Color1}/weaponcatalog: {Color2}Allows you to change the current active weapon catalog.
        ///{Color1}/addallscore: {Color2}Increases the score of all players by a specified amount.
        ///{Color1}/addcoins: {Color2}Increases [rest of string was truncated]&quot;;.
        /// </summary>
        /// <remarks>Change drivers: CD-15 (root; command set)</remarks>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Color1}Capture the Flag is an open source project. 
        ///{Color1}Check out its official repository: 
        ///{Color2}https://github.com/DevD4v3/Capture-The-Flag
        ///{Color1}Creator and programmer: {Color2}DevD4v3 (David Roman)
        ///{Color1}Mappers:{Color2} 
        ///DragonZafiro, Elorreli, amirab, JamesT85,
        ///TheYoungCapone, B4MB1[MC], iMaster, mihaibr,
        ///UnuAlex, SpikY_, Niktia_Ruchkov, Amads, denis_32,
        ///Samarchai, haubitze, Ghost-X, Zniper, Dr.Pawno,
        ///SENiOR, saawan, Risq, Famous, Leo and Pyraeus.
        ///{Color1}Acknowledgments to:{Color [rest of string was truncated]&quot;;.
        /// </summary>
        /// <remarks>Change drivers: CD-15 (root; command set)</remarks>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Color1}This is a capture the flag game mode for SA-MP (San Andreas Multiplayer).
        ///{Color2}There are 2 flags on the map, one for each team. 
        ///Players need to capture the enemy&apos;s flag and bring it back to their own one.
        ///{Color1}Gameplay:{Color2}
        ///The Alpha team plays against the Beta team. 
        ///The aim is to carry the enemy&apos;s flag to the spawn of the own flag. 
        ///The own flag needs to be at the spawn to score. 
        ///So you have to conquer the opponent&apos;s flag and defend your own team&apos;s one at the same time. 
        ///It&apos;s n [rest of string was truncated]&quot;;.
        /// </summary>
        /// <remarks>Change drivers: CD-15 (root; command set)</remarks>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Color1}/maps: {Color2}Displays a list of available maps in the game.
        ///{Color1}/settimeleft: {Color2}Sets the remaining time for the current game session.
        ///{Color1}/returnflag: {Color2}Returns the flag of a specific team to its base position.
        ///{Color1}/gungameon: {Color2}Enables GunGame mode.
        ///{Color1}/gungameoff: {Color2}Disables GunGame mode.
        ///{Color1}/startrt: {Color2}Starts the rotation timer for the current map.
        ///{Color1}/stoprt: {Color2}Stops the rotation timer for the current map.
        ///{Color1}/showrm: { [rest of string was truncated]&quot;;.
        /// </summary>
        /// <remarks>Change drivers: CD-15 (root; command set)</remarks>
        internal static string Moderator {
            get {
                return ResourceManager.GetString("Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Color1}/help: {Color2}Display an introduction to the Capture the Flag mode.
        ///{Color1}/credits: {Color2}Show credits for the game and contributors.
        ///{Color1}/ranks: {Color2}List the different player ranks and their requirements.
        ///{Color1}/mystats: {Color2}Display the statistics of the current player.
        ///{Color1}/stats: {Color2}Show the statistics of a specified player.
        ///{Color1}/tstats: {Color2}Display the statistics of the teams (Alpha and Beta).
        ///{Color1}/changepass: {Color2}Change your account password.
        ///{ [rest of string was truncated]&quot;;.
        /// </summary>
        /// <remarks>Change drivers: CD-15 (root; command set)</remarks>
        internal static string Public1 {
            get {
                return ResourceManager.GetString("Public1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Color1}/topkills: {Color2}Display the list of top players based on their total number of kills.
        ///{Color1}/topspree: {Color2}Display the list of top players based on their maximum killing spree.
        ///{Color1}/team: {Color2}Switch to a different team.
        ///{Color1}/kill: {Color2}Eliminate your character for respawn purposes.
        ///{Color1}/p: {Color2}Allows the player to get a parachute.
        ///{Color1}/re: {Color2}Reset the statistics of the current player.
        ///{Color1}/admins: {Color2}List the current server administrators.
        ///{C [rest of string was truncated]&quot;;.
        /// </summary>
        /// <remarks>Change drivers: CD-15 (root; command set)</remarks>
        internal static string Public2 {
            get {
                return ResourceManager.GetString("Public2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Color1}/armour: {Color2}Grants you temporary armour, reducing damage taken from attacks.
        ///{Color1}/health: {Color2}Restores a portion of your health instantly.
        ///{Color1}/saw: {Color2}Deploys a powerful saw to cut through obstacles or defeat enemies.
        ///{Color1}/spray: {Color2}Releases a spray that can confuse and distract opponents.
        ///{Color1}/teargas: {Color2}Deploys tear gas, impairing visibility and causing disorientation to nearby enemies.
        ///{Color1}/givemecoins: {Color2}Awards you with in-game coins, enha [rest of string was truncated]&quot;;.
        /// </summary>
        /// <remarks>Change drivers: CD-15 (root; command set)</remarks>
        internal static string VIP {
            get {
                return ResourceManager.GetString("VIP", resourceCulture);
            }
        }
    }
}
